### ISSUE TITLE
Forum auf Moodle

### ISSUE THREAD

**Issue by timobornfleth** [ablaette/learningR#12]
Ich denke es wäre im Sinne vieler Studierender hier, wenn es ein Moodle Forum zum einfachen Austausch kleinerer Probleme gäbe. Könnten Sie so etwas einrichten?
Zur Erinnerung dieses Issue

Grüße
Timo

**Comment by ablaette** [comment]
Vielen Dank für diesen Reminder. Das Forum ist eingerichtet, es findet sich bei dem Kurs im Vorspann (bei Ankündigungen etc). Dort auch ein Link auf die Issues, die zum Einsatz kommen sollten, wenn schnelle und dreckige Hilfe im Forum noch nicht zum Ergebnis führt.
