### ISSUE TITLE
Frage | Lösungsweg Übungsaufgabe 1

### ISSUE THREAD

**Issue by jolyngutschmidt** [ablaette/learningR#2]
Hallo zusammen, 
ich habe mich heute mal an der Übungsaufgabe 1 versucht. Zunächst dachte ich, dass damit begrenzte Alterskategorien (21-30, 31-40,...) gemeint sind und habe folgenden Code versucht:

```
today <- 2020
today

age <- (today-(bt2013[["vn2c"]]))

round(table(age)/length(age)*100, 2)

round(mean(age),2)

?cut

agecut <- (cut(age, breaks=c(20,30,40,50,60,Inf), labels=c("0-20","21-30","31-40","41-50","51-60")))
round(table(agecut)/length(agecut)*100, 2)
```

Später habe ich dann gemerkt, dass nach Ü20, Ü30 etc. gefragt war und habe spontan folgende Lösung entdeckt:

```
nrow(subset(df, age >20))

age_val <- c(nrow(subset(df, age >20)), nrow(subset(df, age >30)), nrow(subset(df, age >40)), nrow(subset(df, age >50)))
                                      
age_val <- round(age_val/3911,2)

names(age_val) <- age_cat
age_val
```

Es funktioniert so, habe aber das Gefühl, dass ich hier zu umständlich gedacht habe. Hat hier jemand eine schönere Lösung gefunden? 

Beste Grüße

**Comment by PolMine** [comment]
Schon ziemlich gut! Von meiner Seite erstmal nur kleine Hinweise zum Schreiben von Issues und zur Code-Gestaltung. 

Eine gute Praxis ist, dass Code-Beispiele vollständig ausführbar sind. Das heißt, ich habe Laden von gles und den Aufruf des Datensatzes vorangestellt. Dann habe ich bisschen in Sachen Klammern verschlankt und Leerzeichen eingefügt, was den Code besser lesbar macht.

```r
library(gles)
data(bt2013)

today <- 2020
age <- today - bt2013[["vn2c"]] # hier habe ich überflüssige Klammern entfernt

round(table(age) / length(age) * 100, 2) # durch Leerzeichen etwas besser lesbar

round(mean(age), 2) # Durchschnittsalter

agecut <- cut(
  age,
  breaks = c(20, 30, 40, 50, 60, Inf),
  labels = c("0-20", "21-30", "31-40", "41-50", "51-60")
)

round(table(agecut) / length(agecut) * 100, 2)
```

**Comment by jolyngutschmidt** [comment]
Oh, vielen Dank für die vielen Hinweise! 
Das sieht tatsächlich schon deutlich übersichtlicher aus.

**Comment by ablaette** [comment]
Hier eine alternative Lösung ... 

```r
library(gles)
data(bt2013)

today <- 2013
age <- today - bt2013[["vn2c"]] # hier habe ich überflüssige Klammern entfernt
decade <- round(age / 10, 0) * 10 
age_cohorts <- table(decade)
```
Leider nicht das gleiche Ergebnis. Müssen wir prüfen!

**Comment by ablaette** [comment]
Hier die von Brunn-Lösung!

```r
age_older_20 <- age[age >= 20]
age_older_20_younger_30 <- age_older_20[age_older_20 < 30]
length(age_older_20_younger_30)
```
Bitte gegencheckn!
