### ISSUE TITLE
GLES not available

### ISSUE THREAD

**Issue by alexandranaumann** [ablaette/learningR#3]
Ich habe am Anfang das Paket GLES heruntergeladen und damit gearbeitet. Dann hat es nicht mehr funktioniert und ich habe es deinstalliert. Wenn ich das Paket jetzt neu installieren möchte, dann kommt die Meldung, dass GLES für meine R Version nicht verfügbar ist. 

Warning in install.packages package ‘gles’ is not available (for R version 3.6.3)

Wie kann ich am besten fortfahren?

**Comment by PolMine** [comment]
Danke für die Rückmeldung!

Unter Umständen muss ich das Paket für Ihr System gezielt bereit stellen. Dazu brauche ich noch die Information, ob Sie unter Windows/macOS/Linux arbeiten. Und kopieren Sie bitte auch in Ihre Antwort ein was Sie sehen, wenn Sie diesen Befehl eingeben:

```r
sessionInfo()
```

**Comment by alexandranaumann** [comment]
Danke für die schnelle Antwort! 
Ich arbeite mit Windows. 
Wenn ich sessionInfo() eingebe, kommt Folgendes heraus: 

```{r}
> sessionInfo() R version 3.6.3 (2020-02-29) 
Platform: x86_64-w64-mingw32/x64 (64-bit) 
Running under: Windows 10 x64 (build 18362)  

Matrix products: default  

locale: 
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252   
[3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                    [5] LC_TIME=German_Germany.1252      

attached base packages: 
[1] stats     graphics  grDevices utils     datasets  methods   base
       
loaded via a namespace (and not attached): 
[1] compiler_3.6.3 tools_3.6.3
--
```

**Comment by ablaette** [comment]
Leider habe ich keine Möglichkeit, für (die alte) R-Version 3.6.3 das gles-Paket als "binary package" vorzubereiten. Ich kann allerdings die neue Version des gles-Pakets als Quellpaket bereit stellen. Diese können Sie von unserem PolMine-drat-Repo wie folgt installieren:

```r
drat::addRepo("polmine")
getOption("repos") # polmine.github.com/drat sollte dabei sein
install.packages("gles", type = "source") # hier: Quellpaket installieren, nicht binary!
packageVersion("gles") # das sollte jetzt 0.2.1 sein
```

Voraussetzung für die Installation von Quellpaketen ist bei Windows eine Installation von RTools.

Als Test, ob Sie die Daten aufrufen können:

```r
library(gles)
data(bt2017nw)
```

**Comment by ablaette** [comment]
Wenn Sie doch auf R 4.0.0 updaten, können Sie mit diesen Befehlen alle unter 3.6 installierten Pakete (neu) installieren.

```r
drat::addRepo("polmine")
new_lib_path <- .libPaths()
old_lib_path <- gsub("4\\.0", "3.6", new_lib_path)
pkgs_old_rversion <- list.files(old_lib_path)
for (pkg in pkgs_old_rversion){
  install.packages(pkg)
}
```
Ich habe das bei mir nicht getestet. Feedback welcome!
